<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Facepunch.Steamworks" Version="2.3.3" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="WriteSteamAppId" AfterTargets="Build">
    <Copy SourceFiles="$(PkgFacepunch_Steamworks)\content\steam_api64.dll" DestinationFiles="$(OutputPath)steam_api64.dll" SkipUnchangedFiles="false" OverwriteReadOnlyFiles="true" />
    <WriteLinesToFile File="$(OutputPath)steam_appid.txt" Lines="457140" Overwrite="true" />
  </Target>
</Project>
